export const STATUSES_OPTIONS = [
  {
    label: 'Adicionado',
    value: 'placed'
  },
  {
    label: 'Aprovado',
    value: 'approved'
  },
  {
    label: 'Enviado',
    value: 'shipped'
  },
  {
    label: 'Entregue',
    value: 'delivered'
  },
  {
    label: 'Cancelado',
    value: 'cancelled'
  }
];

export const BOOLEAN_OPTIONS = [
  {
    label: 'Sim',
    value: true
  },
  { label: 'Não', value: false }
];
export const CURRENCY_OPTIONS = [
  { value: 'AED', label: 'AED - UAE Dirham' },
  { value: 'AFN', label: 'AFN - Afghani' },
  { value: 'ALL', label: 'ALL - Lek' },
  { value: 'AMD', label: 'AMD - Armenian Dram' },
  { value: 'ANG', label: 'ANG - Netherlands Antillian Guilder' },
  { value: 'AOA', label: 'AOA - Kwanza' },
  { value: 'ARS', label: 'ARS - Argentine Peso' },
  { value: 'AUD', label: 'AUD - Australian Dollar' },
  { value: 'AWG', label: 'AWG - Aruban Guilder' },
  { value: 'AZN', label: 'AZN - Azerbaijanian Manat' },
  { value: 'BAM', label: 'BAM - Convertible Marks' },
  { value: 'BBD', label: 'BBD - Barbados Dollar' },
  { value: 'BDT', label: 'BDT - Taka' },
  { value: 'BGN', label: 'BGN - Bulgarian Lev' },
  { value: 'BHD', label: 'BHD - Bahraini Dinar' },
  { value: 'BIF', label: 'BIF - Burundi Franc' },
  { value: 'BMD', label: 'BMD - Bermudian Dollar (customarily known as Bermuda Dollar)' },
  { value: 'BND', label: 'BND - Brunei Dollar' },
  { value: 'BOB', label: 'BOB - Boliviano boliviano' },
  { value: 'BRL', label: 'BRL - Brazilian Real' },
  { value: 'BSD', label: 'BSD - Bahamian Dollar' },
  { value: 'BWP', label: 'BWP - Pula' },
  { value: 'BYR', label: 'BYR - Belarussian Ruble' },
  { value: 'BZD', label: 'BZD - Belize Dollar' },
  { value: 'CAD', label: 'CAD - Canadian Dollar' },
  { value: 'CDF', label: 'CDF - Congolese Franc' },
  { value: 'CHF', label: 'CHF - Swiss Franc' },
  { value: 'CLP', label: 'CLP - Chilean Peso' },
  { value: 'CNY', label: 'CNY - Yuan Renminbi' },
  { value: 'COP', label: 'COP - Colombian Peso' },
  { value: 'CRC', label: 'CRC - Costa Rican Colon' },
  { value: 'CUP', label: 'CUP - Cuban Peso' },
  { value: 'CUC', label: 'CUC - Cuban Peso Convertible' },
  { value: 'CVE', label: 'CVE - Cape Verde Escudo' },
  { value: 'CZK', label: 'CZK - Czech Koruna' },
  { value: 'DJF', label: 'DJF - Djibouti Franc' },
  { value: 'DKK', label: 'DKK - Danish Krone' },
  { value: 'DOP', label: 'DOP - Dominican Peso' },
  { value: 'DZD', label: 'DZD - Algerian Dinar' },
  { value: 'EEK', label: 'EEK - Kroon' },
  { value: 'EGP', label: 'EGP - Egyptian Pound' },
  { value: 'ERN', label: 'ERN - Nakfa' },
  { value: 'ETB', label: 'ETB - Ethiopian Birr' },
  { value: 'EUR', label: 'EUR - Euro' },
  { value: 'FJD', label: 'FJD - Fiji Dollar' },
  { value: 'FKP', label: 'FKP - Falkland Islands Pound' },
  { value: 'GBP', label: 'GBP - Pound Sterling' },
  { value: 'GEL', label: 'GEL - Lari' },
  { value: 'GHS', label: 'GHS - Cedi' },
  { value: 'GIP', label: 'GIP - Gibraltar Pound' },
  { value: 'GMD', label: 'GMD - Dalasi' },
  { value: 'GNF', label: 'GNF - Guinea Franc' },
  { value: 'GTQ', label: 'GTQ - Quetzal' },
  { value: 'GYD', label: 'GYD - Guyana Dollar' },
  { value: 'HKD', label: 'HKD - Hong Kong Dollar' },
  { value: 'HNL', label: 'HNL - Lempira' },
  { value: 'HRK', label: 'HRK - Croatian Kuna' },
  { value: 'HTG', label: 'HTG - Gourde' },
  { value: 'HUF', label: 'HUF - Forint' },
  { value: 'IDR', label: 'IDR - Rupiah' },
  { value: 'ILS', label: 'ILS - New Israeli Sheqel' },
  { value: 'BTN', label: 'BTN - Bhutanese Ngultrum' },
  { value: 'INR', label: 'INR - Indian Rupee' },
  { value: 'IQD', label: 'IQD - Iraqi Dinar' },
  { value: 'IRR', label: 'IRR - Iranian Rial' },
  { value: 'ISK', label: 'ISK - Iceland Krona' },
  { value: 'JMD', label: 'JMD - Jamaican Dollar' },
  { value: 'JOD', label: 'JOD - Jordanian Dinar' },
  { value: 'JPY', label: 'JPY - Yen' },
  { value: 'KES', label: 'KES - Kenyan Shilling' },
  { value: 'KGS', label: 'KGS - Som' },
  { value: 'KHR', label: 'KHR - Riel' },
  { value: 'KMF', label: 'KMF - Comoro Franc' },
  { value: 'KPW', label: 'KPW - North Korean Won' },
  { value: 'KRW', label: 'KRW - Won' },
  { value: 'KWD', label: 'KWD - Kuwaiti Dinar' },
  { value: 'KYD', label: 'KYD - Cayman Islands Dollar' },
  { value: 'KZT', label: 'KZT - Tenge' },
  { value: 'LAK', label: 'LAK - Kip' },
  { value: 'LBP', label: 'LBP - Lebanese Pound' },
  { value: 'LKR', label: 'LKR - Sri Lanka Rupee' },
  { value: 'LRD', label: 'LRD - Liberian Dollar' },
  { value: 'LTL', label: 'LTL - Lithuanian Litas' },
  { value: 'LVL', label: 'LVL - Latvian Lats' },
  { value: 'LYD', label: 'LYD - Libyan Dinar' },
  { value: 'MAD', label: 'MAD - Moroccan Dirham' },
  { value: 'MDL', label: 'MDL - Moldovan Leu' },
  { value: 'MGA', label: 'MGA - Malagasy Ariary' },
  { value: 'MKD', label: 'MKD - Denar' },
  { value: 'MMK', label: 'MMK - Kyat' },
  { value: 'MNT', label: 'MNT - Tugrik' },
  { value: 'MOP', label: 'MOP - Pataca' },
  { value: 'MRO', label: 'MRO - Ouguiya' },
  { value: 'MUR', label: 'MUR - Mauritius Rupee' },
  { value: 'MVR', label: 'MVR - Rufiyaa' },
  { value: 'MWK', label: 'MWK - Kwacha' },
  { value: 'MXN', label: 'MXN - Mexican Peso' },
  { value: 'MYR', label: 'MYR - Malaysian Ringgit' },
  { value: 'MZN', label: 'MZN - Metical' },
  { value: 'NGN', label: 'NGN - Naira' },
  { value: 'NIO', label: 'NIO - Cordoba Oro' },
  { value: 'NOK', label: 'NOK - Norwegian Krone' },
  { value: 'NPR', label: 'NPR - Nepalese Rupee' },
  { value: 'NZD', label: 'NZD - New Zealand Dollar' },
  { value: 'OMR', label: 'OMR - Rial Omani' },
  { value: 'PAB', label: 'PAB - Balboa' },
  { value: 'PEN', label: 'PEN - Nuevo Sol' },
  { value: 'PGK', label: 'PGK - Kina' },
  { value: 'PHP', label: 'PHP - Philippine Peso' },
  { value: 'PKR', label: 'PKR - Pakistan Rupee' },
  { value: 'PLN', label: 'PLN - Zloty' },
  { value: 'PYG', label: 'PYG - Guarani' },
  { value: 'QAR', label: 'QAR - Qatari Rial' },
  { value: 'RON', label: 'RON - New Leu' },
  { value: 'RSD', label: 'RSD - Serbian Dinar' },
  { value: 'RUB', label: 'RUB - Russian Ruble' },
  { value: 'RWF', label: 'RWF - Rwanda Franc' },
  { value: 'SAR', label: 'SAR - Saudi Riyal' },
  { value: 'SBD', label: 'SBD - Solomon Islands Dollar' },
  { value: 'SCR', label: 'SCR - Seychelles Rupee' },
  { value: 'SDG', label: 'SDG - Sudanese Pound' },
  { value: 'SEK', label: 'SEK - Swedish Krona' },
  { value: 'SGD', label: 'SGD - Singapore Dollar' },
  { value: 'SHP', label: 'SHP - Saint Helena Pound' },
  { value: 'SLL', label: 'SLL - Leone' },
  { value: 'SOS', label: 'SOS - Somali Shilling' },
  { value: 'SRD', label: 'SRD - Surinam Dollar' },
  { value: 'STN', label: 'STN - Dobra' },
  { value: 'SVC', label: 'SVC - El Salvador Colon' },
  { value: 'SYP', label: 'SYP - Syrian Pound' },
  { value: 'SZL', label: 'SZL - Lilangeni' },
  { value: 'THB', label: 'THB - Baht' },
  { value: 'TJS', label: 'TJS - Somoni' },
  { value: 'TMT', label: 'TMT - Manat' },
  { value: 'TND', label: 'TND - Tunisian Dinar' },
  { value: 'TOP', label: "TOP - Pa'anga" },
  { value: 'TRY', label: 'TRY - Turkish Lira' },
  { value: 'TTD', label: 'TTD - Trinidad and Tobago Dollar' },
  { value: 'TWD', label: 'TWD - New Taiwan Dollar' },
  { value: 'TZS', label: 'TZS - Tanzanian Shilling' },
  { value: 'UAH', label: 'UAH - Hryvnia' },
  { value: 'UGX', label: 'UGX - Uganda Shilling' },
  { value: 'USD', label: 'USD - US Dollar' },
  { value: 'UYU', label: 'UYU - Peso Uruguayo' },
  { value: 'UZS', label: 'UZS - Uzbekistan Sum' },
  { value: 'VEF', label: 'VEF - Bolivar Fuerte' },
  { value: 'VND', label: 'VND - Dong' },
  { value: 'VUV', label: 'VUV - Vatu' },
  { value: 'WST', label: 'WST - Tala' },
  { value: 'XAF', label: 'XAF - CFA Franc BEAC' },
  { value: 'XAG', label: 'XAG - Silver' },
  { value: 'XAU', label: 'XAU - Gold' },
  { value: 'XBA', label: 'XBA - Bond Markets Units European Composite Unit (EURCO)' },
  { value: 'XBB', label: 'XBB - European Monetary Unit (E.M.U.-6)' },
  { value: 'XBC', label: 'XBC - European Unit of Account 9(E.U.A.-9)' },
  { value: 'XBD', label: 'XBD - European Unit of Account 17(E.U.A.-17)' },
  { value: 'XCD', label: 'XCD - East Caribbean Dollar' },
  { value: 'XDR', label: 'XDR - SDR' },
  { value: 'XFU', label: 'XFU - UIC-Franc' },
  { value: 'XOF', label: 'XOF - CFA Franc BCEAO' },
  { value: 'XPD', label: 'XPD - Palladium' },
  { value: 'XPF', label: 'XPF - CFP Franc' },
  { value: 'XPT', label: 'XPT - Platinum' },
  { value: 'XTS', label: 'XTS - Codes specifically reserved for testing purposes' },
  { value: 'YER', label: 'YER - Yemeni Rial' },
  { value: 'ZAR', label: 'ZAR - Rand' },
  { value: 'LSL', label: 'LSL - Lesotho Loti' },
  { value: 'NAD', label: 'NAD - Namibia Dollar' },
  { value: 'ZMK', label: 'ZMK - Zambian Kwacha' },
  { value: 'ZWL', label: 'ZWL - Zimbabwe Dollar' }
];
